FROM postgres:16-bookworm
RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-16-postgis-3 \
    && rm -rf /var/lib/apt/lists/*
COPY init-postgis.sql /docker-entrypoint-initdb.d/10-postgis.sql
